### PR TITLE
Update old class names.

### PR DESCRIPTION
**Pull request by mikicho**

### CODE REVIEW

**Comment by Randonee** [comment]
It's been a while since I've worked with android. Would the androidAPIVersion need to be updated in build.bases for this to work?
This file:
https://github.com/Randonee/BasisAndroid/blob/master/example/build.basis

**Comment by mikicho** [comment]
This is up to your installed api isn't? Personally in my current project I'm using with 23 api so my build.basis looks like that:

```
<target name="Android6.0">
    <appName value="BarbackAssistance" />
    <source path="src" />
    <builddir path="build" />
    <target name="android" type="android">
        <appBuildNumber value="1" />
        <appVersion value="1.0" />
        <androidAPIVersion value="23" />
        <appPackage value="bellboy.BarbackAssistance" />
        <main classpath="ApplicationMain" />
        <resourceDir path="res" />
        <emulator use="true" />
        <debug value="true" />
        <runWhenFinished value="true" />
    </target>
</target>
```

**Comment by Randonee** [comment]
Is using the new api why the changes are needed? 
I think it's a good change but means that there will be no backwards compatibility with old versions.

**Comment by mikicho** [comment]
I'm working with the librery recently and it's little awakward(and it's ok because it's 0.1.0)
If you want we can work on this together.
- Change the build.hxml without need to change the template in the library and rebuild.
- Fix array support for "values" macro (RMacros.hx/buildString() -> strings.xml)
- Get rid of android.jar externs it's should  be done with -java-lib only(BTW -java-lib are not included in the recent release).
- Fix folders hierarchy, maybe it's just to me, but it's little weird.
- Create a little script for automatically install the application on build with android's adb.
- Create integration with "adb logcat"
- Cancel "MainView" the starting point should be MainActivity.
  and more...

**Comment by Randonee** [comment]
All sounds great. I'm not sure how much time I can dedicate currently but I would like to move this project forward. Any work you do is appreciated and I'll help as much as I can.

**Pull request closed without merging**
